### ISSUE TITLE
Pressing print screen causes severe graphical issues

### ISSUE THREAD

**Issue by OBlankenship** [SlavicPotato/SSEDisplayTweaks#4]
Issue persists without any ENBs or other graphical modifications installed. Pressing print screen immediately causes a glitched overlay that persists until the game is exited. If print screen is pressed several times (varies, but approximately 3-5) the game will crash.

Seems to be related to new AMD GPU drivers. 

![image](https://github.com/SlavicPotato/SSEDisplayTweaks/assets/24227844/ae566049-f52d-4299-a0a7-a53cc07aaf86)

**Comment by OBlankenship** [comment]
Tracked the issue down to this setting

SwapEffect=auto

**Comment by SlavicPotato** [comment]
They probably broke something tied to microsoft's directflip mode. You can switch to the old underperforming bitblt presentation model (discard), but I suggest you downgrade the drivers instead or try exclusive fullscreen. Mind that their drivers have had issues with this stuff in the past.

I can't do anything about it since I don't have access to a radeon card and even if that weren't the case, the problem is in the drivers, not the mod.
